### ISSUE TITLE
Can't resolve '../rsme.css' in '.../node_modules/react-social-media-embed/dist/components/embeds'

### ISSUE THREAD

**Issue by timomak** [justinmahar/react-social-media-embed#1]
Your nmp won't compile for me. 

I'm using `"react-social-media-embed": ^1.0.9`

It says 
`Can't resolve '../rsme.css' in '/Users/.../node_modules/react-social-media-embed/dist/components/embeds'`

I noticed you do have a rsme.css in your src/components. Unforutanelty your dist/components doesn't have that file.

**Comment by justinmahar** [comment]
Hey @timomak, thanks for the heads up, this package is evolving rapidly so that was a total oversight! 

I'm going to remove that file altogether and will have that patched sometime this evening most likely.

**Comment by justinmahar** [comment]
@timomak

I just release [v1.0.10](https://www.npmjs.com/package/react-social-media-embed) which should fix the issue. Let me know if that works for you!

**Comment by timomak** [comment]
Beautiful, thank you! That's fixed, but I found another bug when compiling this npm. I'll open a new ticket!
