### ISSUE TITLE
React 18

### ISSUE THREAD

**Issue by elliottpost** [justinmahar/react-social-media-embed#10]
Hi there -- any plans on updating the package requirements to allow React 18? Currently getting this error when trying to install on a React 18.1 project:

```
npm ERR! Found: react@18.1.0
npm ERR! node_modules/react
npm ERR!   react@"^18.1.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^17.0.2" from react-social-media-embed@2.0.12

```

**Comment by justinmahar** [comment]
Hey! Thanks for the heads up. I'll get that fixed up this evening.

**Comment by justinmahar** [comment]
All set. Give it a shot and close if it's fixed for you.

**Comment by elliottpost** [comment]
It works! Sorry for the week long delay in my response.

**Comment by justinmahar** [comment]
No prob. Awesome!
