### ISSUE TITLE
use data-instgrm-captioned

### ISSUE THREAD

**Issue by marcosvspimenta** [justinmahar/react-social-media-embed#12]
How can I use data-instgrm-captioned (option to show post text) in case of instagram?

**Comment by justinmahar** [comment]
hey @marcosvspimenta! Thanks for pointing this out. I'll look into adding support for this via a prop for that embed component.

**Comment by justinmahar** [comment]
@marcosvspimenta Added this to the latest version. 

To install:

```
npm i react-social-media-embed@latest
```

You can now specify the `captioned` prop to show the caption. See the [live example here](https://justinmahar.github.io/react-social-media-embed/?path=/docs/embeds-instagramembed--main-example).

<img width="338" alt="Screenshot at Oct 31 18-11-47" src="https://user-images.githubusercontent.com/3472836/199120035-1e13a3d5-3442-4bf8-915d-c40ffbc4a4eb.png">
