### ISSUE TITLE
Feature request : Option to change height of <img> in embeds

### ISSUE THREAD

**Issue by himsrv2501** [justinmahar/react-social-media-embed#13]
I wan't to display embeds side by side, but they are having different heights.
Using `height` attribute changes the embed height, instead of contained elements.
If there is an option to specify `img` height, it will help in solving the issue.

![image](https://user-images.githubusercontent.com/108259032/176120460-1d269725-917a-4324-9983-5d1023c0e3b0.png)

**Comment by justinmahar** [comment]
Hey @himsrv2501! Thanks for opening an issue about this. I'll look into ways to add support for this. We may be up to the mercy of Instagram, as their script is responsible for rendering the content/elements in the embed container, but the might be a way to modify this manually.

**Comment by justinmahar** [comment]
This doesn't seem possible and the issue has been quiet for some time. Closing for now.
