### ISSUE TITLE
Facebook embed issues

### ISSUE THREAD

**Issue by viacheslav-antonenko** [justinmahar/react-social-media-embed#16]
Hi. There are a couple of issues I found while using the FacebookEmbed component.
1. Some posts don't adapt to the size we set in the width prop for FacebookEmbed, and their content gets cut. For example this [post](https://www.facebook.com/eDopomogaGov/posts/pfbid0MdUttRHrVEpnwDnqRjosdLfSk7h1nvnb7qkB9emyvD7mdXjm5XW6WWoJ2utHAUp1l) 

2. When users aren't logged in to Facebook and we use URL to Facebook posts, embed posts don't render. Instead, we see some text saying: "This Facebook post is no longer available. It may have been deleted or its privacy settings have been changed", even though those posts are publicly open. Also in Firefox, those posts aren't rendered even though you're logged in to Facebook. In your demo, you use the URL to some old post (short id to post), that Facebook doesn't use anymore. And that kind of post renders when users aren't logged in to Facebook. Maybe there is a way to somehow render those kinds of posts. Or at least to view some text saying that the user needs to log in to Facebook to view those posts.

**Comment by tengri** [comment]
I only see the loader and text "View post on Facebook"

**Comment by gregghawes** [comment]
> I only see the loader and text "View post on Facebook"

Same

**Comment by Shobe-MO** [comment]
> I only see the loader and text "View post on Facebook"

Also same.

**Comment by adam-marostica-nl** [comment]
I have fixed this locally by adding the necessary "data-width" attribute to FacebookEmbed.js. This resolves the issue for me.

**Comment by vc-ca** [comment]
Thanks so much @adam-marostica-nl 

this fixed the IG component

`  <InstagramEmbed
                    url={imgLink}
                    width={600}
                    dataWith={600}
                  />`

**Comment by david-alpert-nl** [comment]
we are seeing facebook posts refuse to load with console.log errors stating it is due to HTTP headers of `x-frame-origin: deny` served by Facebook's servers, which we cannot seem to workaround on our side.

**Comment by justinmahar** [comment]
@david-alpert-nl Please confirm that you are using the correct post URL for the facebook post. See the instructions I posted here: https://github.com/justinmahar/react-social-media-embed/issues/14#issuecomment-1297458134

You can try the post URL from the blockquote cite attribute using the [example demo](https://justinmahar.github.io/react-social-media-embed/?path=/docs/embeds-facebookembed--main-example).

**Comment by justinmahar** [comment]
@tengri @Shobe-MO @gregghawes Added a section to the docs that may help - [How do you get a Facebook post URL?](https://github.com/justinmahar/react-social-media-embed#how-do-you-get-a-facebook-post-url). The correct URL is kinda hard to find.

**Comment by justinmahar** [comment]
@viacheslav-antonenko @adam-marostica-nl @vc-ca I've added a data-width attribute to Facebook and IG, and these are now part of the published package in npm. Hopefully that takes care of the sizing issues people were seeing.

**Comment by justinmahar** [comment]
@viacheslav-antonenko For issue 2 you pointed out, can you provide a link to a problematic facebook post?

**Comment by justinmahar** [comment]
Closing for now. Open a new issue if the problem persists.
