### ISSUE TITLE
YoutubeEmbed Component not showing up.

### ISSUE THREAD

**Issue by reuel-freitas** [justinmahar/react-social-media-embed#17]
I'm using this library in my project, it's a great job. The InstagramEmbed working perfectly, but the YoutubeEmbed is not showing up. I try to put a placeholderImg, and initially it shows the image, and then the comonent disappears. I took some prints for you
![teste](https://user-images.githubusercontent.com/54087058/178833209-30b57ea8-e99d-4be7-82f3-89dee9a62753.jpeg)
.

**Comment by patodeveloperka** [comment]
hi, I cave the same problem with facebook; it doesn't show up. does anyone know how to fix it?

**Comment by vc-ca** [comment]
This now seems to be happening with IG embed as well.

Check the main IG example:

[https://justinmahar.github.io/react-social-media-embed/?path=/docs/embeds-instagramembed--main-example](https://justinmahar.github.io/react-social-media-embed/?path=/docs/embeds-instagramembed--main-example
)

**Comment by vc-ca** [comment]
#16 FB + IG Embeds are fixable by adding a 'data-width' prop

`<InstagramEmbed url={imgLink} width={600} dataWith={600} />`

**Comment by justinmahar** [comment]
Hey y'all. Glad you figured out a solution to this -- this weekend I'll look into building a solution into the library, or at least add something to the docs to account for this

**Comment by justinmahar** [comment]
@patodeveloperka Confirm you are using the correct URL for the facebook post. I added instructions to this issue, check it out and give it another shot: https://github.com/justinmahar/react-social-media-embed/issues/14#issuecomment-1297458134

**Comment by justinmahar** [comment]
@reuel-freitas I can't seem to recreate the issue on my end, and the [demo site example](https://justinmahar.github.io/react-social-media-embed/?path=/docs/embeds-youtubeembed--main-example) is working fine. Any way you could share a link to the code sandbox you're seeing the problem in? FYI the YouTube embed is not my own code, I'm using the [react-youtube](https://www.npmjs.com/package/react-youtube) package to do the heavy lifting there. Maybe codesandbox itself is blocking the embed?

**Comment by justinmahar** [comment]
Closing for now. Open a new issue if the problem persists.
