### ISSUE TITLE
TikTok & Instagram embeds opening in browser on page load in iOS React Native

### ISSUE THREAD

**Issue by nathan-logan** [justinmahar/react-social-media-embed#18]
React version: 17.0.2
Package version: 2.2.2

iOS 16, works fine on Android.

We are using React Native's webview to serve our site, and when the page loads it automatically attempts to deep link into both TikTok & Instagram apps after the components mount.

https://user-images.githubusercontent.com/37327997/191157572-3fcea125-49de-4b2a-b371-3b2f5c845000.MP4

**Comment by nathan-logan** [comment]
Solution was to add instagram & tiktok to [React Native Webview's origin whitelist](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#originwhitelist)

**Comment by magnum6actual** [comment]
I just started looking at this component. I'm wanting to embed TikTok and others into a react native app.  So - do I understand correctly that you're using react-social-media-embed in react from your web server into a react-native webview?

**Comment by kaushiksahoo2000** [comment]
@magnum6actual i am looking to do the same thing. did you go with the same approach?
