### ISSUE TITLE
Facebook Refused to display '<URL>' in a frame because it set 'X-Frame-Options' to 'deny'.

### ISSUE THREAD

**Issue by PeterHueer** [justinmahar/react-social-media-embed#22]
No Facebook embed will be load.

Error message:
Refused to display '<URL>' in a frame because it set 'X-Frame-Options' to 'deny'.

Reproducable on your Storybook Facebook section:
https://justinmahar.github.io/react-social-media-embed/?path=/story/embeds-facebookembed--main-example

**Comment by PeterHueer** [comment]
Ok it's reproducable in Safari. 

<img width="749" alt="image" src="https://user-images.githubusercontent.com/43515255/206186062-5b2f9fa4-f654-4eae-bfb3-012322a46377.png">

**Comment by justinmahar** [comment]
Hmm interesting. Kinda stumped on this one as this library is entirely client-side. From what I've gathered, Safari defaults to `DENY`, and Facebook would need to explicitly send an X-Frame-Options header value for it to work in Safari. Only solution I can come up with is to use a proxy.

**Comment by PeterHueer** [comment]
Another option could be to use the embed (iframe) from facebook and exchange the url's. Or is there a reason why you preferred the sdk?

**Comment by PeterHueer** [comment]
i got it to work @justinmahar  by loading the script not in the iframe but in my application. After the script is loaded and im sure the div is rendered I execute the fb init function. if i find time i can try to get this running in the package. What do you think?

```jsx
  const [scriptLoaded, setScriptLoaded] = React.useState(false);
  const [fbRef, setFbRef] = React.useState<HTMLDivElement | null>();

```
```jsx
 React.useEffect(() => {
    if (!fbRef) return;
    if (!isInitialized) return;
    setIsLoading(true);
    window.FB.init({
      xfbml: true,
      version: "v15.0",
    });
    FB.Event.subscribe("xfbml.render", () => setIsLoading(false));
  }, [fbRef, url, scriptLoaded, isInitialized]);
```

```jsx
  return (
    <>
      <Script
        id="fb_init"
        src="https://connect.facebook.net/en_US/sdk.js"
        onLoad={() => setScriptLoaded(true)}
      />
      {isLoading ||
        (loading && (
          <PortraitFormatSkeleton
            aria-label="Facebook skeleton"
            width={`${SOCIAL_MEDIA_MIN_WIDTH}px`}
            height={`${SOCIAL_MEDIA_MIN_HEIGHT}px`}
          />
        ))}
      <div
        ref={setFbRef}
        aria-label={`Facebook post ${deeplink}`}
        className="fb-post"
        data-href={deeplink}
        data-width={SOCIAL_MEDIA_WIDTH}
      />
    </>
  );
```

**Comment by wesleybl** [comment]
This error occurs when we are not logged into Facebook.  Updating the sdk version, the problem is fixed. I created the PR:

#35

**Comment by justinmahar** [comment]
Thanks to @wesleybl for the fix. Just shipped the update to npm. 

To install:

```
npm i react-social-media-embed@latest
```
