### ISSUE TITLE
YouTubeEmbed not displaying.

### ISSUE THREAD

**Issue by erictaylor** [justinmahar/react-social-media-embed#23]
Same issue as #17 and as for the comment there, opened a new issue.

Came across the same problem today @justinmahar. I found that forcing the dependency to `react-youtube` to the latest `10.1.0` version fixed the issue.

I reviewed the breaking changes between the existing dependency version and the latest and found that none of the changes are applicable to the usage in this library (currently). I think it would be safe to bump the dependency up.

Happy to submit a PR to do so if desired.

**Comment by justinmahar** [comment]
@erictaylor Just pushed an update.

```
npm install react-social-media-embed@latest
```

Give that a shot and let me know if that fixes it.

**Comment by erictaylor** [comment]
Thanks @justinmahar. I'll give this a try next week, though I'm confident this will work given I fixed it locally with dependency resolutions. I'll close this since I'm confident in the fix.
