### ISSUE TITLE
FacebookEmbed doesn't works

### ISSUE THREAD

**Issue by matiasj899** [justinmahar/react-social-media-embed#25]
Hello, I'm using the facebook embed component like the example but i have this two errors and the post doesn't seems load. Please help.
![image](https://user-images.githubusercontent.com/67933270/208890988-60ad7cf3-1d6e-401e-8415-9f4611a17bcc.png)

![image](https://user-images.githubusercontent.com/67933270/208890267-a5a5d8c3-6a76-4d02-a64c-3ca8cfcd0b60.png)
![image](https://user-images.githubusercontent.com/67933270/208890411-6f3956db-a60f-48c1-bd48-07643c665ec1.png)

**Comment by justinmahar** [comment]
Hmm not seeing that on the [demo page](https://justinmahar.github.io/react-social-media-embed/?path=/story/embeds-facebookembed--main-example) for FacebookEmbed, so it seems to be working once deployed. Are you seeing this only locally or does it occur once deployed?

**Comment by justinmahar** [comment]
Closing until further notice.
