### ISSUE TITLE
Can't change the height and width for most of the social embeds

### ISSUE THREAD

**Issue by timomak** [justinmahar/react-social-media-embed#3]
When I try setting the height or width to a social embed like so:

`<InstagramEmbed
    url="https://www.instagram.com/p/CUbHfhpswxt/"
    width="100%"
  />`
  
  I can't get the height or width to change. 
  
  It only works on Twitter, LinkedIn, and Youtube for me.
  
  I'm programming on `"react": "^16.13.1"` typescript.

**Comment by justinmahar** [comment]
Sizing is by far the biggest pain with these embeds. They all behave a little differently. So I've left things up to the embed itself unless you specify a size. Percentages are the trickiest it seems.

I'll see what I can do to make it easy to size things. I think the use cases are:
- I want to size it to a specific width (and sometimes height).
- I want to center the embed in the current container.

Is there another use case you're looking for? I think those two cover it for the most part. Will look into adding stories to cover these explictly.
