### ISSUE TITLE
Tiktok embedding have extra padding

### ISSUE THREAD

**Issue by zeghmouri** [justinmahar/react-social-media-embed#32]
Hello everyone I am trying to embed a tiktok video into my React appand that's the result

![image](https://user-images.githubusercontent.com/52124045/216853093-1cd0b865-4eef-404d-a865-aafaf5cb9b2d.png)

As you can see the video is wrapped inside a div (with white background) that have padding how can I remove that or hiw can I change the background color so it fits my website background.

**Comment by zeghmouri** [comment]
I made the background of my site Red so you can see what I mean

![image](https://user-images.githubusercontent.com/52124045/216853337-cfdaffd6-a320-4cf9-b94f-18aa86cae083.png)

**Comment by jmmrte** [comment]
Ran into this in another issue (#5), the solution was:

> If you size any of the embeds with a width (non-percentage), you should be able to add a background color to the surrounding container.

Check out that other issue, and give that a try.

**Comment by justinmahar** [comment]
Ran into this in another issue (#5), the solution was:

> If you size any of the embeds with a width (non-percentage), you should be able to add a background color to the surrounding container.

Check out that other issue, and give that a try.

**Comment by zeghmouri** [comment]
Thanx @justinmahar,
But I solved it by applying a negative left margin to the iframe
```css
.tiktok-embed-container iframe{
        margin-left: -68px;
}
```
and I have fixed the width of the embed to 325px (the width of the video).
With this I have removed the extra padding.
