### ISSUE TITLE
Type Error on InstagramEmbed

### ISSUE THREAD

**Issue by sectsect** [justinmahar/react-social-media-embed#37]
Getting the property 'style' not defined error while using in TypeScript:

```tsx
<InstagramEmbed
  style={{
    maxWidth: 540,
  }}
  url={url}
  width="100%"
/>
```

```shell
error TS2322: Type '{ style: { maxWidth: number; }; url: string; width: string; }' is not assignable to type 'IntrinsicAttributes & InstagramEmbedProps'.
  Property 'style' does not exist on type 'IntrinsicAttributes & InstagramEmbedProps'.

19           style={{
             ~~~~~

[4:06:24 PM] Found 1 error. Watching for file changes.
```

**Comment by justinmahar** [comment]
Hmm I'm a bit stumped on this one. The demo site uses the style attribute for the fluid width, like you're doing, so I'm not sure why TS is complaining for you. 

If I add `style` to the embed, it autocompletes and successfully determines the source of the `style` type, `React.HTMLAttributes<HTMLDivElement>`:

<img width="780" alt="Screenshot at Mar 29 16-49-32" src="https://user-images.githubusercontent.com/3472836/228664286-be93cd3b-47b4-48e6-95d0-af98ecf3c2f7.png">

The only think I can think is to check your version of TypeScript. The project is being built with TS 4.9.4.

```
"typescript": "^4.9.4",
```

**Comment by sectsect** [comment]
I reinstalled and ran.
The details are as follows.
```
npm uninstall react-social-media-embed && npm install react-social-media-embed@latest
```

I also tried the following, but it didn't work.
```
rm -rf node_modules && rm package-lock.json
npm i
```

### package.json
```json
"dependencies": {
  "react-social-media-embed": "^2.3.5",
  ...
},
"devDependencies": {
  "typescript": "^4.9.4"
  ...
},
```

### Instagram.tsx
```tsx
import type { NextPage } from 'next';
import { InstagramEmbed } from 'react-social-media-embed';

interface Props {
  instagramId: string;
}

const Instagram: NextPage<Props> = ({ instagramId: id }) => {
  const url = `https://www.instagram.com/p/${id}/`;

  return (
    <div className="py-4 md:py-6">
      <InstagramEmbed
        style={{
          maxWidth: 540,
        }}
        className="max-w-[540px]"
        url={url}
        width="100%"
      />
    </div>
  );
};

export default Instagram;
```

```tsx
src/components/elements/Instagram/Instagram.tsx:15:11 - error TS2322: Type '{ style: { maxWidth: number; }; url: string; width: string; }' is not assignable to type 'IntrinsicAttributes & InstagramEmbedProps'.
  Property 'style' does not exist on type 'IntrinsicAttributes & InstagramEmbedProps'.

15           style={{
             ~~~~~

[1:33:18 PM] Found 1 error. Watching for file changes.
```

<img src="https://user-images.githubusercontent.com/5554826/228733880-9cdb7d4e-17cc-4c90-ad80-d8435f94e32d.jpg" width="375">


### FYI
The `className` prop also seems to throw an error.

<img src="https://user-images.githubusercontent.com/5554826/228733579-3b921308-8763-479c-95e5-de143cee5ff7.jpg" width="700">

**Comment by sectsect** [comment]
As a test, Adding the `style` property to the interface manually seems to fix this error.

`InstagramEmbed.d.ts`

```diff
import * as React from 'react';
import { DivProps } from 'react-html-props';
import { Frame } from '../hooks/useFrame';
import { PlaceholderEmbedProps } from '../placeholder/PlaceholderEmbed';
export interface InstagramEmbedProps extends DivProps {
    url: string;
    width?: string | number;
    height?: string | number;
    linkText?: string;
    /** Deprecated -- This has no effect. Captions are always visible due to https://github.com/justinmahar/react-social-media-embed/issues/26 */
    captioned?: boolean;
    placeholderImageUrl?: string;
    placeholderSpinner?: React.ReactNode;
    placeholderSpinnerDisabled?: boolean;
    placeholderProps?: PlaceholderEmbedProps;
    embedPlaceholder?: React.ReactNode;
    placeholderDisabled?: boolean;
    scriptLoadDisabled?: boolean;
    retryDelay?: number;
    retryDisabled?: boolean;
    igVersion?: string;
    frame?: Frame;
    debug?: boolean;
+   style?: React.CSSProperties;
}
export declare const InstagramEmbed: ({ url, width, height, linkText, placeholderImageUrl, placeholderSpinner, placeholderSpinnerDisabled, placeholderProps, embedPlaceholder, placeholderDisabled, scriptLoadDisabled, retryDelay, retryDisabled, igVersion, frame, debug, ...divProps }: InstagramEmbedProps) => JSX.Element;

```

**Comment by justinmahar** [comment]
So the props for className and style come from a TypeScript alias library called react-html-props. 

Perhaps adding that to your dev dependencies will shake some sense into the TS compiler?

**Comment by sectsect** [comment]
@justinmahar 

Yes. Adding the dependency directly to the project solves the problem.

**Comment by sectsect** [comment]
@justinmahar 

It looks like can't reach types in `react-html-props`.
It indicates that it is not bundled in production as it is a development dependency.

Maybe we should move `react-html-props` to `dependencies` (from `devDependencies`).

FYI: This problem does not occur on `npm link` environment.

**Comment by micahjsmith** [comment]
in my TS project I also had to install `react-html-props` into `dependencies` (as well as `@types/youtube-player` into `devDependencies`)

**Comment by justinmahar** [comment]
As of v2.5.5, both `react-html-props` and `@types/youtube-player` are now in `dependencies` instead of `devDependencies`)
