### ISSUE TITLE
Disable showing captions

### ISSUE THREAD

**Issue by Shain-Dholakiya** [justinmahar/react-social-media-embed#46]
The documentation says that hiding caption for instagram is disabled and I saw the reasoning as well. But it seems like it works for me when getting rid of the caption data tag. Can this be added back? Instagram gives you the option to include or exclude the caption when embedding as well.
<img width="390" alt="Screen Shot 2023-07-10 at 10 10 06 AM" src="https://github.com/justinmahar/react-social-media-embed/assets/88295404/722614d3-e358-48a9-a5b9-39ae955f2314">

**Comment by matbrgz** [comment]
I just remove the code:
`"data-instgrm-captioned": false, `
 from
`node_modules\.pnpm\react-social-media-embed@2.3.6_react-dom@18.2.0_react@18.2.0\node_modules\react-social-media-embed\dist\components\embeds\InstagramEmbed.js`
and then: 
![image](https://github.com/justinmahar/react-social-media-embed/assets/23284276/27dd414e-9a9c-4750-9de0-8df363b08216)

Now we have to change the code to reflect this.
