### ISSUE TITLE
Background Colors on Emebeds

### ISSUE THREAD

**Issue by timomak** [justinmahar/react-social-media-embed#5]
TikTok has a white background that wraps the TikTok Embed itself. 

The Facebook Embed doesn't have a background color at all and it is transparent. (Which is honestly pretty cool cause it allows me to set the color by changing the background of the parent container.) It's not a bug, it's a feature ;)

**Comment by justinmahar** [comment]
I'll look into the bg colors and try to make them a bit more consistent. I looked at tiktok yesterday and it looks like the embed itself has a white background that they set. We might be able to get around this by setting the size of the containing div and centering it. Stay tuned.

**Comment by timomak** [comment]
Awesome! That would be great! I added an image under another issue that pertains to this TikTok Embed.

**Comment by justinmahar** [comment]
@timomak I've added docs in the README for how to center embeds. I believe this addresses the main concern you had. Will reply to the other issue with a screenshot of the workaround to the TikTok issue.

**Comment by justinmahar** [comment]
If you size any of the embeds with a width (non-percentage), you should be able to add a background color to the surrounding container.

**Comment by timomak** [comment]
That's a great tip! Thank you! I think you solved all the issues involved with this!
