### ISSUE TITLE
YouTube Shorts support

### ISSUE THREAD

**Issue by jj0e** [justinmahar/react-social-media-embed#59]
Are embeds for YouTube shorts currently supported? I tried to use the existing `YouTubeEmbed` component which a YouTube shorts url and it does not load the video.

**Comment by justinmahar** [comment]
Hey @jj0e! I'm using [react-youtube](https://www.npmjs.com/package/react-youtube) under the hood for YT embeds, not sure if that library supports shorts yet. Will look into adding support for this when I have a chance. Might need to build out a separate embed component if they're a different beast.

**Comment by justinmahar** [comment]
@jj0e I've added support for YouTube Shorts. 

You can see the [demo here](https://justinmahar.github.io/react-social-media-embed/?path=/story/embeds-youtubeembed--you-tube-shorts).

Shorts are 16:9, so be sure to specify a width and height in that aspect ratio, such as 225x400.

```bash
npm i react-social-media-embed@latest
```

Grab the latest version and give it a shot.
