### ISSUE TITLE
Youtube Missing Props Error

### ISSUE THREAD

**Issue by timomak** [justinmahar/react-social-media-embed#6]
When trying to add a YouTube Embed as such
`<YouTubeEmbed
        url='https://www.youtube.com/watch?v=HpVOs5imUN0'
        width='100%'
        height={220}
        placeholderImageUrl='https://i.ytimg.com/vi/HpVOs5imUN0/maxresdefault.jpg?t=Date.now()'
      />`

I get the following error
`Property 'youTubeProps' is missing in type '{ url: string; width: string; height: number; placeholderImageUrl: string; }' but required in type 'YouTubeEmbedProps'.`

It only happens on the Youtube Embed.

I'm programming on `"react": "^16.13.1"` typescript.

**Comment by justinmahar** [comment]
Nice catch! I'll have a fix for this ready sometime this evening.

**Comment by justinmahar** [comment]
Should be fixed.

```
npm i react-social-media-embed@latest
```

**Comment by timomak** [comment]
This worked for me! Thank you! Although I ended up not using this package for the youtube embed since the previews were coming up a lower quality than `react-player`.

Happy to switch if that's changed as well! Although I still like their Twitch and SoundCloud emebed. 

I also ended up using the simple iframe to be able to embed the Spotify links since it wasn't too complex. I'm happy to share the code if you're looking to continue working on adding more embeds!

**Comment by justinmahar** [comment]
Awesome! I don't blame you for switching to that. I'm on the fence whether I should pull YT out of this library or not, but for my own projects it just makes it convenient if it's included here. Might add an option to SoundCloud at some point but it'll just be a wrapper around react-player. I think I'm calling this project a wrap for the time being.

**Comment by justinmahar** [comment]
Heads up, found a potential bug with IG retry logic when you're not using the default placeholder. Fixed that. It's an edge case, but to be on the safe side, I'd use the latest release.

```
npm i react-social-media-embed@latest
```

With that I believe I'm done with this library for now. Thanks for all of your feedback!
