### ISSUE TITLE
[Twitter] cdn.syndication.twimg.com - 404 Not Found

### ISSUE THREAD

**Issue by edshkliaruk** [justinmahar/react-social-media-embed#64]
We faced an issue with loading the embedded Twitter. Many errors appear in the console, and details regarding the error are in the screenshot.

Does anyone know anything about this?

<img width="1092" alt="Screenshot 2023-12-16 at 21 00 39" src="https://github.com/justinmahar/react-social-media-embed/assets/125352863/20cfd12f-db0f-4197-8995-01bb187d5856">
<img width="629" alt="Screenshot 2023-12-16 at 21 00 56" src="https://github.com/justinmahar/react-social-media-embed/assets/125352863/594be5da-2cdc-42ad-9a74-885aeba0b1b8">

**Comment by justinmahar** [comment]
Hey @edshkliaruk! Hmm... first thing that comes to mind is to try to rule out browser interference by using an incognito tab, and/or ensure all of your browser extensions are disabled, particularly ad blockers. If you're using Brave browser, try Shields down mode for the page. After that, see if you're still getting the errors.

**Comment by justinmahar** [comment]
FYI under the hood this library uses the [react-twitter-embed](https://www.npmjs.com/package/react-twitter-embed) library, so any issues affecting Twitter in react-social-media-embed would be coming from that. If you're still running into the problem, I can see if updating the Twitter library addresses the issues you're seeing.

**Comment by edshkliaruk** [comment]
@justinmahar hey, I checked this in Safari, in Chrome, and in Chrome Incognito, the error still occurs. I checked the demos of the react-twitter-embed library, and there Twitter also does not load

**Comment by edshkliaruk** [comment]
What I see the last commit of react-twitter-embed was pushed 2 years ago. It looks like twitter updated something.

**Comment by edshkliaruk** [comment]
@justinmahar I assume, this issue ticket can be closed, because it is not reproducible at all. But still it is strange issue.

**Comment by justinmahar** [comment]
Yep, looks like things are back to working again. Love it when problems fix themselves! 

Cheers
