### ISSUE TITLE
Instagram loading spinner has UI defect.

### ISSUE THREAD

**Issue by stupendusmagneficus** [justinmahar/react-social-media-embed#65]
![Screenshot 2024-01-03 at 16 43 14](https://github.com/justinmahar/react-social-media-embed/assets/76649500/5417e39c-2ac0-4b0e-9d92-36b684fe800b)

Instagram loading spinner on the right side has grey line.

**Comment by FilipiRafael** [comment]
Hey bro, did you solve it?

**Comment by justinmahar** [comment]
This one confounded me when I was building this package. Couldn't figure out a way to hide this, even with clipping via the overflow CSS property. 

If you or anyone else can find a way to hide this with CSS I'll incorporate it into the library (or send a PR with the fix)

**Comment by nirav1211** [comment]
Guys did this issue got resolved?
If yes how?
@FilipiRafael @justinmahar @stupendusmagneficus

**Comment by FilipiRafael** [comment]
> Guys did this issue got resolved? If yes how? @FilipiRafael @justinmahar @stupendusmagneficus

Yes, I did but to be honest I do not remember and didn't find the project I was working. But I remember it was something with my app, not the library.

**Comment by JethroNatividad** [comment]
This issue is resolved in #82 
@justinmahar @stupendusmagneficus @nirav1211 @FilipiRafael

**Comment by justinmahar** [comment]
Get the fix via:

```
npm i react-social-media-embed@latest
```
