### ISSUE TITLE
No caption block in embedded Instagram

### ISSUE THREAD

**Issue by oliverfg** [justinmahar/react-social-media-embed#69]
The caption block does not appear in the embedded instagram.

I'm using 2.5.9 version of the package.

In the official documentation not work either
![image](https://github.com/justinmahar/react-social-media-embed/assets/37214361/afa45900-8e16-4eb7-b503-47cfaff5d2be)

Is there a necessary step for it to appear that I have skipped?

**Comment by alex-20min** [comment]
Hey @oliverfg we solved it by adding a prop "captioned" to the component:
`<InstagramEmbed url={url} captioned />`

**Comment by justinmahar** [comment]
Re-added official support for this.

Live example here:

https://justinmahar.github.io/react-social-media-embed/?path=/story/embeds-instagramembed--main-example-with-captions
