### ISSUE TITLE
LinkedInEmbed does not work on Brave

### ISSUE THREAD

**Issue by pierotoscano1496** [justinmahar/react-social-media-embed#70]
I was testing my React application on different browsers, but LinkedinEmbed component does not work when I run my app on Brave, there is nothing rendered. I was checking on the official web:
![image](https://github.com/justinmahar/react-social-media-embed/assets/32021208/d45f7abe-494b-4f3c-bdba-cfd465624622)

Meanwhile on Chrome:
![image](https://github.com/justinmahar/react-social-media-embed/assets/32021208/6b993ec0-ceec-4e9b-9c91-bb7f11a3c84f)

**Comment by justinmahar** [comment]
Hey @pierotoscano1496! This is most likely Brave blocking the social media post. Buried in Settings -> Shields is a setting "Allow LinkedIn embedded posts" -- I believe that is off by default. Try toggling that on and see if the embed works then

![SCR-20240324-jfng](https://github.com/justinmahar/react-social-media-embed/assets/3472836/97c8d784-124d-45ad-811d-942cc1e71fe5)

**Comment by justinmahar** [comment]
Awesome! You're welcome
