### ISSUE TITLE
Instagram Embeddings no longer work on desktop because of CORB issue but works on mobile

### ISSUE THREAD

**Issue by justerenoir** [justinmahar/react-social-media-embed#79]
Instagram embeddings no longer work for desktop in all browsers because of CORB issue. But it works on my mobile device.

**Comment by didierganthier** [comment]
Any update on that? I've been facing the same issue

**Comment by justerenoir** [comment]
> Any update on that? I've been facing the same issue

No, I have been scrambling to find a solution but not much people are talking about it or looking for a solution.

**Comment by matheusdamiao** [comment]
Nothing yet? Same error here.

**Comment by matheusdamiao** [comment]
Good news: it seems to be fixed. 

Even in the demo page, the instagram post is now displaying and I didn't find the CORB error in the console anymore.
[insta offical demo](https://justinmahar.github.io/react-social-media-embed/?path=/story/embeds-instagramembed--main-example)

**Comment by matheusdamiao** [comment]
@justerenoir you can already close this issue, my friend, as the problem is already solved.
