### ISSUE TITLE
Feature: default volume setting for TikTok

### ISSUE THREAD

**Issue by pthieu** [justinmahar/react-social-media-embed#9]
The package is great and works as needed, just that when the embed video begins to play, the volume is set to full blast.

I looked at your documentation and also TikTok's embed code and there doesn't seem to be any way to set a default volume.
Maybe it's just not documented but figured I'd create an issue here to confirm if it's impossible.

**Comment by justinmahar** [comment]
No volume setting that I'm aware of. TikTok's API is probably the worst out of all of them. Their embed JS documentation is severely lacking and was a huge pain to get working consistently in React.

**Comment by justinmahar** [comment]
If anyone knows how to do this and comes across this issue, please drop a note and I'll add support.

**Comment by pthieu** [comment]
@justinmahar haha I figured as much, oh well no biggie, we'll just have to wait
